config/routes.rb
Rails.application.routes.draw do
resources :characters, only: [:index, :show]

resources :about

resources :search, only: [:index] do
  collection do
  get 'results'
  end
end

get 'search', to: 'search#index'
get 'search/results', to: 'search#results'

  get 'characters/index'
  get 'characters', to: 'characters#index'
  root to: 'characters#index'
  
  get 'characters/:id', to: 'characters#show', id: /\d+/


  get 'about/index'
  get 'about', to: 'about#index'
  root to: 'about#index'


  



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :dogs

  validates :hero, presence: true, uniqueness: true
  validates :location, presence: true
end

app/models/dog.rb
class Dog < ApplicationRecord
    belongs_to :character

    validates :main_breed, presence: true, uniqueness: true
    validates :sub_breed, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all
  end

  def show
    @character = Character.find(params[:id])
  end

  def about
    @characters = Character.all

  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index
    end



    def results
        @characters = Character.where('hero LIKE ?', "%#{params[:q]}%")
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/about/index.html.erb
<h1>About</h1>
<p>I used data from two data sources, one json file for main breeds and sub breeds as well as a faker gem for overwatch heroes</p>

app/views/characters/index.html.erb
<h1>Hero's</h1>

<ul>

    <% @characters.each do |character| %>    
        <li>
        <%= link_to character.hero, character %>
        </li>
    <% end %>
</ul>

app/views/characters/show.html.erb
<h1><%= @character.hero %> </h1>
<p><b>Hero's Location :</b> <%= @character.location %>  </p>
<p><b>Hero's Dog Breed :</b>   </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Introproject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>



  </head>

  <body>
  <header>
  <h1>a</h1>
  
 
  <a class="btn btn-primary"<%= link_to 'Search', search_index_path %></a>
  

  


    


    <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" <%= link_to 'Overwatch Heroes and their Pets', root_path %></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
      <!-- Example row of columns -->
      <%= yield %>
      <hr>

      <footer>
      <div class="row">
        <div class="col-md-4">
          <h2>About us</h2>
          <p>We are a website that tells you about you're favourite OverWatch Heroes :) </p>
          <p><a class="btn btn-default" role="button"<%= link_to 'View details',  about_index_path  %></a></p>
        </div>
        <div class="col-md-4">
          <h2>Contact us</h2>
          <p>For any business inquiries contact me at Jontmcintosh@hotmail.com / jmcintosh45@academic.rrc.ca or at 204-770-0695</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Check out op.gg</h2>
          <p>Check out op.gg for other amazing game related content!!! </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>
        <p>&copy; 2018 Company, Inc.</p>
      </footer>
    </div> <!-- /container -->
    <footer>
    </footer>
  </body>



  


</html>

app/views/search/index.html.erb
<h2>Search for a Hero</h2>

<%= form_tag(results_search_index_path, method: "get") do %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
<% end %>

app/views/search/results.html.erb
<h2> Hero/Hero's Found </h2>


<% if @characters.empty? %>
    <p>Sorry, no hero found with that name.</p>
    <% else %>
    <ul>
    <% @characters.each do |character| %>
            <li><%= link_to character.hero, character %></li>
    <% end %>
    </ul>
<% end %>